paths:
  /api/products/:
    get:
      summary: Obtiene todos los productos
      tags:
        - Products
      parameters:
        - in: query
          name: limit
          schema:
            type: integer
          description: Limite de resultados obtenidos en la consulta. Por defecto, 10.

        - in: query
          name: page
          schema:
            type: integer
          description: Número de página consultada actualmente.

        - in: query
          name: sort
          schema:
            type: integer
          description: Ordenar precio ascendente o descendente. Por defecto, 1 (ascendente).

        - in: query
          name: queryType
          schema:
            type: string
          description: Nombre del campo en el cual se desea filtrar los documentos.

        - in: query
          name: queryValue
          schema:
            type: string
          description: Valor en el campo queryType en el cual se desea filtrar los documentos.

      responses:
        "200":
          description: Los productos fueron obtenidos de la base de datos satisfactoriamente
        "500":
          description: Fallo interno del servidor

    post:
      summary: Añade un producto
      tags:
        - Products
      parameters:
        - in: body
          name: product
          required: true
          schema:
            type: object
          description: Datos del nuevo producto a añadir.
      responses:
        "200":
          description: Producto añadido satisfactoriamente
        "401":
          description: No autorizado para añadir un producto
        "500":
          description: Fallo interno del servidor

  /api/products/{pid}:
    get:
      summary: Obtiene un producto por su ID
      tags:
        - Products
      parameters:
        - in: path
          name: pid
          required: true
          schema:
            type: string
          description: ID del producto que se desea obtener.
      responses:
        "200":
          description: Producto obtenido satisfactoriamente
        "404":
          description: No se encontró el producto
        "500":
          description: Fallo interno del servidor

    put:
      summary: Actualiza un producto
      tags:
        - Products
      parameters:
        - in: path
          name: pid
          required: true
          schema:
            type: string
          description: ID del producto que se desea actualizar.
        - in: body
          name: product
          required: true
          schema:
            type: object
          description: Datos actualizados del producto.
      responses:
        "200":
          description: Producto actualizado satisfactoriamente
        "401":
          description: No autorizado para actualizar el producto
        "404":
          description: No se encontró el producto
        "500":
          description: Fallo interno del servidor

    delete:
      summary: Elimina un producto
      tags:
        - Products
      parameters:
        - in: path
          name: pid
          required: true
          schema:
            type: string
          description: ID del producto que se desea eliminar.
      responses:
        "200":
          description: Producto eliminado satisfactoriamente
        "401":
          description: No autorizado para eliminar el producto
        "404":
          description: No se encontró el producto
        "500":
          description: Fallo interno del servidor
